apiVersion: v1
kind: Secret
metadata:
  name: sso-secret
  namespace: sso
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.Secret.POSTGRES_PASSWORD | b64enc }}
  AUTH_SAML_STATE_SIGNING_KEY: {{ .Values.Secret.AUTH_SAML_STATE_SIGNING_KEY | b64enc }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.Secret.GOOGLE_OAUTH_CLIENT_ID | b64enc }}
  API_GOOGLE_OAUTH_CLIENT_ID: {{ .Values.Secret.API_GOOGLE_OAUTH_CLIENT_ID | b64enc }}
  APP_GOOGLE_OAUTH_CLIENT_ID: {{ .Values.Secret.APP_GOOGLE_OAUTH_CLIENT_ID | b64enc }}
  AUTH_DB: {{ .Values.Secret.AUTH_DB | b64enc }}
