apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    #nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 800m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '9600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '9600'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt  
spec:
  rules:
  - host: sso-auth.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 80
  tls:
  - hosts:
    - sso-auth.example.com
    secretName:  sso-auth.example.com-tls