apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: sso-api
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.SSO_PORT }}
      targetPort: {{ .Values.SSO_PORT }}    